coffee_shop/coffee_shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("products.urls")),
    path("admin/", admin.site.urls),
    path("usuarios/", include("users.urls")),
    path("pedidos/", include("orders.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coffee_shop/orders/urls.py
from django.urls import path
from orders.views import MyOrderView, CreateOrderProductView

urlpatterns = [
    path("mi-orden/", MyOrderView.as_view(), name="my_order"),
    path("agregar-producto/", CreateOrderProductView.as_view(), name="add_product"),
]

coffee_shop/products/urls.py
from django.urls import path
from .views import ProductFormView, ProductListView, ProductListAPI

urlpatterns = [
    path("", ProductListView.as_view(), name="list_product"),
    path("api/", ProductListAPI.as_view(), name="list_product_api"),
    path("agregar/", ProductFormView.as_view(), name="add_product"),
]

coffee_shop/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

urlpatterns = [
    path("login/", LoginView.as_view(template_name="users/login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("registro/", RegisterView.as_view(), name="register"),
]

coffee_shop/orders/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)
    order_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Order {self.id} por {self.user}"


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.order} - {self.product}"

coffee_shop/products/models.py
from django.db import models


# Create your models here.
class Product(models.Model):
    name = models.TextField(max_length=200, verbose_name="nombre")
    description = models.TextField(max_length=500, verbose_name="descripcion")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="precio")
    available = models.BooleanField(default=True, verbose_name="disponible")
    photo = models.ImageField(
        upload_to="logos", null=True, blank=True, verbose_name="foto"
    )

    def __str__(self):
        return self.name

coffee_shop/users/models.py
from django.db import models

# Create your models here.

coffee_shop/orders/forms.py
from django.forms import ModelForm
from .models import OrderItem


class OrderProductForm(ModelForm):
    class Meta:
        model = OrderItem
        fields = ["product"]

coffee_shop/products/forms.py
from django import forms
from .models import Product


class ProductForm(forms.Form):
    name = forms.CharField(label="Nombre", max_length=200)
    description = forms.CharField(label="Descripcion", max_length=500)
    price = forms.DecimalField(label="Precio", max_digits=10, decimal_places=2)
    available = forms.BooleanField(initial=True, label="Disponible", required=False)
    photo = forms.ImageField(label="Foto", required=False)

    def save(self):
        Product.objects.create(
            name=self.cleaned_data["name"],
            description=self.cleaned_data["description"],
            price=self.cleaned_data["price"],
            available=self.cleaned_data["available"],
            photo=self.cleaned_data["photo"],
        )

coffee_shop/orders/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from .models import Order, OrderItem
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import OrderProductForm


# Create your views here.
class MyOrderView(LoginRequiredMixin, ListView):
    model = Order
    template_name = "orders/my_order.html"
    context_object_name = "order"

    def get_object(self, queryset=None):
        return Order.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["active_orders"] = Order.objects.filter(
            user=self.request.user, is_active=True
        )
        context["inactive_orders"] = Order.objects.filter(
            user=self.request.user, is_active=False
        )
        return context


class CreateOrderProductView(LoginRequiredMixin, CreateView):
    form_class = OrderProductForm
    template_name = "orders/create_order_product.html"
    success_url = reverse_lazy("my_order")

    def form_valid(self, form):
        order, _ = Order.objects.get_or_create(is_active=True, user=self.request.user)

        # Obtener el producto del formulario
        product = form.cleaned_data["product"]

        # Buscar si ya existe el producto en la orden
        order_item = OrderItem.objects.filter(order=order, product=product).first()
        if order_item:
            form.instance.quantity = (
                order_item.quantity + 1
            )  # Si existe, aumentar cantidad
            order_item.delete()
        else:
            form.instance.quantity = 1  # Si no existe, crearlo y establecer cantidad

        form.instance.order = order  # Establecer la orden en el formulario
        form.instance.save()
        return super().form_valid(form)

coffee_shop/products/views.py
from django.urls import reverse_lazy
from django.views import generic
from rest_framework.views import APIView
from rest_framework.response import Response

from products.models import Product
from .forms import ProductForm
from .serializers import ProductSerializer


# Create your views here.
class ProductFormView(generic.FormView):
    template_name = "products/add_product.html"
    form_class = ProductForm
    success_url = reverse_lazy("list_product")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class ProductListView(generic.ListView):
    template_name = "products/list_products.html"
    model = Product
    context_object_name = "products"


class ProductListAPI(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request):
        products = Product.objects.all()
        serializer = ProductSerializer(products, many=True)
        return Response(serializer.data)

coffee_shop/users/views.py
from django.contrib.auth.forms import UserCreationForm
from django.views import generic
from django.urls import reverse_lazy


class RegisterView(generic.CreateView):
    form_class = UserCreationForm
    template_name = "users/sign_up.html"
    success_url = reverse_lazy("login")

coffee_shop/orders/templates/orders/my_order.html
{% extends "base.html" %}

{% block content %}
<h1 class="text-3xl font-bold mb-4 text-stone-900">Mis ordenes</h1>
<h2 class="text-2xl font-semibold mb-2 text-stone-800">Activas</h2>
<div class="flex flex-wrap space-x-4" style="position: relative; top: 10px;">
    {% for order in active_orders%}
        <div class="max-w-sm rounded overflow-hidden shadow-lg p-4 bg-white mb-4">
            <div class="font-bold text-xl mb-2 text-stone-900">
                ID del pedido: {{ order.id }}
            </div>
            <p class="text-stone-700 text-base mb-4">Fecha: {{ order.order_date|date:"F j, Y" }}</p>
            <ul class="list-disc pl-5 text-stone-700">
                {% for product_order in order.orderitem_set.all %}
                    <li class="flex justify-between">
                        <span>{{ product_order.product.name }}</span>
                        <span>{{ product_order.quantity }} x ${{ product_order.product.price }}</span>
                    </li>
                {% empty %}
                <li>No hay productos en esta orden</li>
                {% endfor %}
            </ul>
        </div>
    {% empty %}
    <p class="text-stone-700">No orders found.</p>
    {% endfor %}
</div>       
<h2 class="text-2xl font-semibold mb-2 text-stone-800">Inactivas</h2>
<div class="flex flex-wrap space-x-4" style="position: relative; top: 10px;">
    {% for order in inactive_orders%}
        <div class="max-w-sm rounded overflow-hidden shadow-lg p-4 bg-white mb-4">
            <div class="font-bold text-xl mb-2 text-stone-900">ID del pedido: {{ order.id }}</div>
                <p class="text-stone-700 text-base mb-4">Fecha: {{ order.order_date|date:"F j, Y" }}</p>
                <ul class="list-disc pl-5 text-stone-700">
                    {% for product_order in order.orderitem_set.all %}
                        <li class="flex justify-between">
                            <span>{{ product_order.product.name }}</span>
                            <span>{{ product_order.quantity }} x ${{ product_order.product.price }}</span>
                        </li>
                    {% empty %}
                    <li>No hay productos en esta orden</li>
                    {% endfor %}
                </ul>
        </div>
    {% empty %}
        <p class="text-stone-700">No orders found.</p>
    {% endfor %}
</div>
                   
{% endblock content %} 

coffee_shop/products/templates/products/add_product.html
{% block content %}
    <h1>Add Product</h1>
    <form action="{% url "add_product" %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Product</button>
    </form>
{% endblock %}

coffee_shop/products/templates/products/list_products.html
{% extends "base.html" %}

{% block content %}
  <h1 class="text-2xl font-bold text-stone-700 sm:text-3xl text-center mt-8 mb-4">
    Lista de productos
  </h1>
  <div class="flex flex-wrap -mx-4">
    {% for product in products %}
      <div class="w-full sm:w-1/2 md:w-1/3 lg:w-1/4 px-4 mb-8">
      <a href="#" class="group relative block overflow-hidden">
        <button
          class="absolute end-4 top-4 z-10 rounded-full bg-white p-1.5 text-stone-800 transition hover:text-stone-900"
        >
          <span class="sr-only">Wishlist</span>
        
          <svg
        xmlns="http://www.w3.org/2000/svg"
        fill="none"
        viewBox="0 0 24 24"
        stroke-width="1.5"
        stroke="currentColor"
        class="size-4"
          >
        <path
          stroke-linecap="round"
          stroke-linejoin="round"
          d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z"
        />
          </svg>
        </button>
        {% if product.photo%}
        <img
        src="{{product.photo.url}}"
        alt="{{product.name}}"
        class="h-64 w-full object-cover transition duration-500 group-hover:scale-105 sm:h-72"
        />
        {% endif %}
        
        <div class="relative border border-gray-100 bg-white p-6">
          <span class="whitespace-nowrap bg-stone-800 px-3 py-1.5 text-xs font-medium text-white"> New </span>
        
          <h3 class="mt-4 text-lg font-medium text-gray-900">{{product.name}}</h3>
        
          <p class="mt-1.5 text-sm text-stone-700">${{product.price}}</p>
        
          <form action="{% url 'add_product' %}" class="mt-4" method="post">
          {% csrf_token %}
          <input type="hidden" name="product" value="{{product.id}}">
        <button
          class="block w-full rounded bg-stone-800 p-4 text-sm font-medium text-white transition hover:bg-stone-900"
        >
          Add to Cart
        </button>
          </form>
        
        </div>
      </a>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

coffee_shop/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coffee Shop</title>
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
</head>
<body class="bg-stone-400">
<header class="bg-stone-600">
    <div class="mx-auto flex h-16 max-w-screen-xl items-center justify-between px-4 sm:px-6 lg:px-8">
        <a class="block text-teal-600" href="{% url 'list_product'%}" style="position: absolute; top: 0; left: 0; margin: 16px;">
            <span class="sr-only">Home</span>
            <img src="{% static 'users/logo.png' %}" alt="Coffee Shop Logo" class="h-20 w-auto bg-white p-1 rounded-full">
        </a>
        <div class="flex items-center gap-4" style="position: absolute; top: 0; right: 60px; margin: 16px;">
            {% if user.is_authenticated %}
            <h1 class="text-2xl font-bold text-stone-900 sm:text-3xl">
                Hola, {{ user.username }}
            </h1>
            <button
                type="button"
                class="overflow-hidden rounded-full border border-gray-300 shadow-inner"
            >
                <span class="sr-only">Toggle dashboard menu</span>
                <img
                src="{% static 'users/avatar.webp' %}"
                alt=""
                class="h-10 w-10 object-cover"
                />
            </button>
            <form action="{% url "logout" %}" method="post" class="inline-flex items-center justify-center">
                {% csrf_token %}
                <button
                type="submit"
                class="overflow-hidden rounded-full border border-gray-300 shadow-inner"
                >
                    <span class="sr-only">Logout</span>
                    <img
                    src="{% static 'users/logout.jpg' %}"
                    alt=""
                    class="h-10 w-10 object-cover"
                    />
                </button>
            </form>
            {% else %}
            <a
                class="block rounded-md bg-stone-800 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-stone-900"
                href="{% url 'login' %}"
            >
                Login
            </a>
            <a
                class="block rounded-md bg-gray-100 px-5 py-2.5 text-sm font-medium text-stone-800 transition hover:text-stone-700/75"
                href="{% url 'register' %}"
            >
                Register
            </a>
            {% endif %}
            <a href="{% url "my_order"%}" class="relative overflow-hidden rounded-full border border-gray-300 shadow-inner transition bg-white hover:bg-stone-300" >
                <span class="sr-only">View shopping cart</span>
                <img
                    src="{% static 'users/cart.png' %}"
                    alt="Shopping Cart"
                    class="h-10 w-10 object-cover"
                />
                </button>
            </a>
        </div>
    </div>
</header>
<div class="container mx-auto px-4 w-full">
    {% block content %}{% endblock %}
</div>
</body>
</html>

coffee_shop/templates/base_entry.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Coffee Shop</title>
    <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
</head>
<body>
    <div class="flex h-screen">
        <div class="w-1/2">
            <img src="{% static 'users\cafe-capuchino.jpg' %}" alt="capuchino" class="h-full w-full object-cover">
        </div>
        <div class="w-1/2 flex items-center justify-center ">
            <div class="container mx-auto px-4 bg-stone-100">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

coffee_shop/users/templates/users/login.html
{% extends "base_entry.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="flex justify-center items-center min-h-screen">
    <div class="w-full max-w-md border-2 border-stone-800 rounded-lg p-6 bg-white">
        <h1 class="text-3xl font-bold text-gray-900 sm:text-4xl mb-4">
            Iniciar sesion
        </h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button
                class="inline-block w-full rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500"
                type="submit">
                Login
            </button>
            <div class="flex items-center justify-between mt-4">
                <p class="text-sm text-gray-500">
                  No tienes cuenta?
                  <a class="underline" href="{% url "register"%}">Registrate</a>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

coffee_shop/users/templates/users/sign_up.html
{% extends "base_entry.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="flex justify-center items-center min-h-screen">
    <div class="w-full max-w-md border-2 border-stone-800 rounded-lg p-6 bg-white">
        <h1 class="text-3xl font-bold text-gray-900 sm:text-4xl">
            Registrate
        </h1>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button
                class="inline-block w-full rounded border border-indigo-600 bg-indigo-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-indigo-600 focus:outline-none focus:ring active:text-indigo-500"
                type="submit">
                Registrarse
            </button>
            <div class="flex items-center justify-between">
                <p class="text-sm text-gray-500">
                  Ya tienes cuenta?
                  <a class="underline" href="{% url "login"%}">Ingresa</a>
                </p>
            </div>
        </form>
    </div>
</div>
{% endblock content %}